repo_url: https://github.com/fga-eps-mds/2026-1-RetinaScan-Doc
repo_name: RetinaScan - Doc

site_name: RetinaScan
theme:
  name: material

  markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

  palette:
    - scheme: default
      accent: indigo
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: "index.md"
  - Metodologia: 
      - Metodologia Aplicada: "metodologia/metodologia-aplicada.md"
      - Comunicação Operacional: "metodologia/comunicacao-operacional.md"
  - Produto:
      - Lean Inception: "produto/lean-inception.md"
      - Canvas MVP: "produto/mvp-canvas.md"
      - Protótipo de Alta Fidelidade: "produto/prototipo-de-alta.md"
      - Identidade Visual: "produto/identidade-visual.md"
      - Backlog do Produto: "produto/backlog-do-produto.md"
  - Planejamento:
      - EAP: "planejamento/EAP.md"
      - Roadmap do Produto: "planejamento/roadmap-do-produto.md"
      - Plano de Gestão de Riscos: "planejamento/plano_de_ger_riscos.md"
      - Plano de Custos: "planejamento/plano_de_custos.md"
  - Projeto:
      - Arquitetura: "projeto/arquitetura.md"
      - Modelagem do Banco de Dados: "projeto/modelagem-do-BD.md"
      - Decisões do Projeto: "projeto/decisoes.md"
      - Modelos de Inteligência Artificial: "projeto/ia/modelos_de_ia.md"
      - Versionamento de Modelos: "projeto/ia/versionamento_modelos.md"
      - Dashboard Analítico: indicadores.md
  - Guia de Contribuição:
      - Código de Conduta: "guia_de_contribuicao/codigo-de-conduta.md"
      - Política de Branches: "guia_de_contribuicao/politica-de-branches.md"
      - Política de Commits: "guia_de_contribuicao/politica-de-commits.md"
  - Atas de Reuniões:
      - PO 23.03.2026: "atas-reunioes/Ata-01-EPS-2026-03-23-PO.md"
      - Equipe 30.03.2026: "atas-reunioes/Ata-02-EPS-2026-03-30.md"
      - PO 01.04.2026: "atas-reunioes/Ata-03-EPS-2026-04-01-PO.md"
      - Equipe 06.04.2026: "atas-reunioes/Ata-04-EPS-2026-04-06.md"
      - PO 06.04.2026: "atas-reunioes/Ata-05-EPS-2026-04-06-PO.md"
      - Equipe 13.04.2026: "atas-reunioes/Ata-06-EPS-2026-04-13.md"
      - PO 13.04.2026: "atas-reunioes/Ata-07-EPS-2026-04-13-PO.md"
      - Equipe 20.04.2026: "atas-reunioes/Ata-08-EPS-2026-04-20.md"
      - PO 20.04.2026: "atas-reunioes/Ata-09-EPS-2026-04-20-PO.md"

